language: python
python:
- '3.6'
notifications:
  email: false
install:
# everything else
- travis_retry pip install .
# coverage packages
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- pip freeze
script:
- coverage run --source=flimage ./setup.py test
- coverage report -m
- codecov
- flake8 flimage
- flake8 examples
- flake8 tests
deploy:
  provider: pypi
  user: "ci_qpi"
  password:
    secure: "Z0Fbti2OZvVV1o8VVBQiJlGfPJCmWLYP2IIEI/dw2HtFjWfu8aC0pOV/aZhR6Yq8cGoJBf2mcAHiBHbjP1yqhUxe9ZpCo4UMHMfse8KcxxOt7R2uSVmKLI4l3d1fhBjE0iF64768ro59gedjjIV4Bv1oWK5Oef74exX53Y1muqrXyZvobHHnk5v/g7ksPfKFCyJc0RCsmDPXzb4Qd63ESetnbmd2xIrVDNPUuRVmlchNmD6NXPJy7nYw5NvWR+s7NJufZKcnLXQ8BWBE9/iH3Vvm3AaZ6OFANWhsCX/sZtlqR7rU81QJPhVATlittYgxJeo6naon7Ytqu9M95jV6L5k5VvjA0DfPaXJ04weDE7MKEj8VGYzDVFrQzsSO+qt7ikrt/q3fbL5FdduXepAeUugDpZoLz+rP5EhlWySIiRn7xVGSKi63UmKpYKsDsnJIrynR36J/zGc72VfFMKiJ7aNGw4OyiR66ZsQN+matTIyC2es5fXRwRfSI1//X5SLLFTFBSwBJnk2mEy7kN3CQwVXjQqlTrtqTV+J8DkEzv2Bbrc5F1Lx4S4w1yjn70qSCUXKj6WKLcJHZeLPfQv6tX240fPcK6xQJiIoYyxDCZgk74p/JJfP5GkMIBPSigwsBTKrtDYsbrFEF+d1+bFeVytwgo1zwjMVs+3ImwS29I94="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
